<a href="https://colab.research.google.com/github/PawaniMekhala/AI-Driven-Student-Dropout-Prediction/blob/main/02_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [14]:
import pandas as pd

data_path = "/content/drive/MyDrive/student-dropout-prediction/data/raw/data.csv"
# Load dataset
df = pd.read_csv(data_path, sep=';')

# df.to_csv("/content/drive/MyDrive/student-dropout-prediction/data/processed/clean_data.csv", index=False)

In [15]:
# Convert Target to binary (Dropout = 1)
df['Dropout'] = df['Target'].apply(lambda x: 1 if x == 'Dropout' else 0)

In [16]:
# check if Convert Target to binary or not (Dropout = 1)
df[['Target', 'Dropout']].head()
df['Dropout'].value_counts()

Dropout
0    3003
1    1421
Name: count, dtype: int64

In [17]:
df.shape

(4424, 38)

In [18]:
df.columns

Index(['Marital status', 'Application mode', 'Application order', 'Course',
       'Daytime/evening attendance\t', 'Previous qualification',
       'Previous qualification (grade)', 'Nacionality',
       'Mother's qualification', 'Father's qualification',
       'Mother's occupation', 'Father's occupation', 'Admission grade',
       'Displaced', 'Educational special needs', 'Debtor',
       'Tuition fees up to date', 'Gender', 'Scholarship holder',
       'Age at enrollment', 'International',
       'Curricular units 1st sem (credited)',
       'Curricular units 1st sem (enrolled)',
       'Curricular units 1st sem (evaluations)',
       'Curricular units 1st sem (approved)',
       'Curricular units 1st sem (grade)',
       'Curricular units 1st sem (without evaluations)',
       'Curricular units 2nd sem (credited)',
       'Curricular units 2nd sem (enrolled)',
       'Curricular units 2nd sem (evaluations)',
       'Curricular units 2nd sem (approved)',
       'Curricular units 2nd sem (grade)',
       'Curricular units 2nd sem (without evaluations)', 'Unemployment rate',
       'Inflation rate', 'GDP', 'Target', 'Dropout'],
      dtype='object')

In [19]:
# REMOVE second-semester column
drop_cols = [
    'Curricular units 2nd sem (credited)',
    'Curricular units 2nd sem (enrolled)',
    'Curricular units 2nd sem (evaluations)',
    'Curricular units 2nd sem (approved)',
    'Curricular units 2nd sem (grade)',
    'Curricular units 2nd sem (without evaluations)'
]

df = df.drop(columns=drop_cols)

In [20]:
# to check if successfully removed second-semester columns or not
df.shape

(4424, 32)

In [21]:
df.columns

Index(['Marital status', 'Application mode', 'Application order', 'Course',
       'Daytime/evening attendance\t', 'Previous qualification',
       'Previous qualification (grade)', 'Nacionality',
       'Mother's qualification', 'Father's qualification',
       'Mother's occupation', 'Father's occupation', 'Admission grade',
       'Displaced', 'Educational special needs', 'Debtor',
       'Tuition fees up to date', 'Gender', 'Scholarship holder',
       'Age at enrollment', 'International',
       'Curricular units 1st sem (credited)',
       'Curricular units 1st sem (enrolled)',
       'Curricular units 1st sem (evaluations)',
       'Curricular units 1st sem (approved)',
       'Curricular units 1st sem (grade)',
       'Curricular units 1st sem (without evaluations)', 'Unemployment rate',
       'Inflation rate', 'GDP', 'Target', 'Dropout'],
      dtype='object')

In [22]:
# Drop original Target column
df = df.drop(columns=['Target'])

In [27]:
X = df.drop(columns=['Dropout'])
y = df['Dropout']

In [28]:
X.shape, y.shape

((4424, 30), (4424,))

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [30]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

In [31]:
y_train.value_counts()
y_train_res.value_counts()

Dropout
1    2402
0    2402
Name: count, dtype: int64

In [32]:
X_train_res.to_csv("X_train_processed.csv", index=False)
y_train_res.to_csv("y_train_processed.csv", index=False)
X_test.to_csv("X_test.csv", index=False)
y_test.to_csv("y_test.csv", index=False)